[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

tab = overload(hyper, tab)

[hyper:C-S-A]


# Remaps the escape key to capslock
# esc = capslock
